project_id = "mckuaytsjvjuvobtxaou"

[functions.gemini-food-search]
verify_jwt = false

[functions.gemini-food-scan]
verify_jwt = false

[functions.ai-coach]
verify_jwt = false

[functions.ai-workout-notifications]
verify_jwt = false

[functions.ai-workout-summary]
verify_jwt = false
